# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install

    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install

    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install

    - name: Build
      uses: CultureHQ/actions-yarn@master
      with:
        args: build
